"use client";

import { Canvas, useFrame } from "@react-three/fiber";
import { Float, MeshDistortMaterial, MeshTransmissionMaterial, OrbitControls, Sparkles } from "@react-three/drei";
import { ArrowLeft, Check, MousePointer2, Rotate3D, Sparkles as SparkleIcon } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import * as THREE from "three";

const variants=[
  {id:"jellyfish",n:"01",name:"Медуза",latin:"JELLYFISH",desc:"Полупрозрачный купол, светящееся ядро и текучие щупальца.",tone:"#ff2435"},
  {id:"sun",n:"02",name:"Солнце",latin:"SOLAR CORE",desc:"Живая плазменная звезда с пульсирующей короной.",tone:"#ff6a24"},
  {id:"mercury",n:"03",name:"Ртуть",latin:"MERCURY",desc:"Холодный жидкий металл и свободные капли на орбите.",tone:"#d9d9de"},
  {id:"lead",n:"04",name:"Свинец",latin:"LEAD MONOLITH",desc:"Тяжёлый матовый монолит с медленной механикой.",tone:"#7d7d86"},
  {id:"plasma",n:"05",name:"Плазменное сердце",latin:"PLASMA HEART",desc:"Горячий энергетический узел с неоновой циркуляцией.",tone:"#ff1844"},
  {id:"blackhole",n:"06",name:"Чёрная дыра",latin:"EVENT HORIZON",desc:"Тёмное ядро, красный диск и искривлённые орбиты.",tone:"#ff3a27"},
  {id:"crystal",n:"07",name:"Нейрокристалл",latin:"NEURAL CRYSTAL",desc:"Острый вычислительный кристалл с сетчатой оболочкой.",tone:"#ff394f"},
  {id:"bloom",n:"08",name:"Огненный цветок",latin:"EMBER BLOOM",desc:"Органические лепестки, раскрывающиеся вокруг ядра.",tone:"#ff5630"},
  {id:"quantum",n:"09",name:"Квантовая лента",latin:"QUANTUM RIBBON",desc:"Бесконечная стеклянная лента в постоянном движении.",tone:"#ff304b"},
  {id:"singularity",n:"10",name:"Сингулярность",latin:"SINGULARITY",desc:"Минималистичное чёрное солнце с алым горизонтом.",tone:"#d90b21"},
] as const;
type VariantId=typeof variants[number]["id"];

function Glass({color="#7b0712"}:{color?:string}){return <MeshTransmissionMaterial color={color} transmission={.98} thickness={1.1} roughness={.06} chromaticAberration={.09} anisotropicBlur={.14} distortion={.38} distortionScale={.35} temporalDistortion={.16} clearcoat={1} samples={4} resolution={256}/>}
function Rotating({children,speed=.15,tilt=.08}:{children:React.ReactNode,speed?:number,tilt?:number}){const ref=useRef<THREE.Group>(null);useFrame((s,d)=>{if(ref.current){ref.current.rotation.y+=d*speed;ref.current.rotation.x=Math.sin(s.clock.elapsedTime*.35)*tilt}});return <group ref={ref}>{children}</group>}

function Jellyfish(){return <Float speed={1.2} floatIntensity={.5}><Rotating speed={.08}><mesh position={[0,.6,0]} scale={[1.45,.82,1.45]}><sphereGeometry args={[1,64,32,0,Math.PI*2,0,Math.PI*.62]}/><Glass color="#780914"/></mesh><mesh position={[0,.35,0]} scale={[1.12,.42,1.12]}><sphereGeometry args={[1,48,24]}/><MeshDistortMaterial color="#370006" emissive="#e60022" emissiveIntensity={2.5} distort={.45} speed={1.4} transparent opacity={.72}/></mesh>{[-.75,-.38,0,.38,.75].map((x,i)=><mesh key={x} position={[x,-.65,0]} rotation={[0,0,x*.35]} scale={[.12,1.2+i%2*.25,.12]}><torusKnotGeometry args={[.42,.1,90,12,2,3]}/><MeshDistortMaterial color="#9d0718" emissive="#ff1834" emissiveIntensity={1.5} distort={.5} speed={1.2+i*.06} transparent opacity={.62}/></mesh>)}</Rotating></Float>}
function Sun(){return <Rotating speed={.06}><mesh scale={1.42}><sphereGeometry args={[1,96,64]}/><MeshDistortMaterial color="#ff3a0b" emissive="#ff2800" emissiveIntensity={3.8} roughness={.58} distort={.5} speed={2.2}/></mesh><mesh scale={1.7}><icosahedronGeometry args={[1,5]}/><meshBasicMaterial color="#ff7a2d" wireframe transparent opacity={.12}/></mesh><pointLight color="#ff4b10" intensity={34} distance={9}/></Rotating>}
function Mercury(){return <Float speed={1.6} rotationIntensity={.5}><Rotating speed={.2}><mesh scale={1.25}><torusKnotGeometry args={[1,.5,220,48,2,3]}/><MeshTransmissionMaterial color="#c7c8cd" transmission={.72} thickness={1.6} roughness={.02} metalness={.75} chromaticAberration={.04} anisotropicBlur={.08} samples={4} resolution={256}/></mesh>{[[1.7,.8,.2],[-1.6,-.8,.3],[1.2,-1.45,-.2]].map((p,i)=><mesh key={i} position={p as [number,number,number]} scale={.18+i*.04}><sphereGeometry args={[1,32,32]}/><meshStandardMaterial color="#dadbe0" metalness={1} roughness={.03}/></mesh>)}</Rotating></Float>}
function Lead(){return <Float speed={.35} floatIntensity={.12}><Rotating speed={.035} tilt={.025}><mesh scale={[1.35,1.7,1.15]} rotation={[.2,.25,.1]}><dodecahedronGeometry args={[1,2]}/><meshStandardMaterial color="#303036" metalness={.92} roughness={.48}/></mesh><mesh scale={[1.36,1.71,1.16]} rotation={[.2,.25,.1]}><dodecahedronGeometry args={[1,1]}/><meshBasicMaterial color="#a2a2aa" wireframe transparent opacity={.12}/></mesh></Rotating></Float>}
function Plasma(){return <Float speed={1.4}><Rotating speed={.18}><mesh scale={1.35}><torusKnotGeometry args={[1,.38,240,42,3,5]}/><MeshDistortMaterial color="#5e0011" emissive="#ff0034" emissiveIntensity={3.4} roughness={.1} distort={.32} speed={2}/></mesh><mesh scale={1.5}><torusKnotGeometry args={[1,.4,140,16,3,5]}/><meshBasicMaterial color="#ff4563" wireframe transparent opacity={.16}/></mesh></Rotating></Float>}
function BlackHole(){return <Rotating speed={.1}><mesh><sphereGeometry args={[.78,64,64]}/><meshStandardMaterial color="#000" roughness={.08} metalness={1}/></mesh>{[0,1,2,3].map(i=><mesh key={i} rotation={[1.25+i*.06,.1,i*.3]} scale={1+i*.18}><torusGeometry args={[1.5,.028+i*.012,10,180]}/><meshBasicMaterial color={i%2?"#ff1d2e":"#ff6b32"} transparent opacity={.7-i*.12}/></mesh>)}<pointLight color="#ff260f" position={[0,0,1]} intensity={18}/></Rotating>}
function Crystal(){return <Float speed={.8} rotationIntensity={.32}><Rotating speed={.13}><mesh scale={1.55}><icosahedronGeometry args={[1,1]}/><MeshTransmissionMaterial color="#650510" transmission={.92} thickness={1.8} roughness={.04} chromaticAberration={.16} anisotropicBlur={.08} samples={4} resolution={256}/></mesh><mesh scale={1.2}><octahedronGeometry args={[1,2]}/><meshBasicMaterial color="#ff1235" wireframe transparent opacity={.5}/></mesh><mesh scale={.5}><icosahedronGeometry args={[1,2]}/><meshBasicMaterial color="#ff1535"/></mesh></Rotating></Float>}
function Bloom(){return <Float speed={1}><Rotating speed={.11}>{Array.from({length:6}).map((_,i)=><mesh key={i} rotation={[0,0,i*Math.PI/3]} position={[Math.cos(i*Math.PI/3)*.72,Math.sin(i*Math.PI/3)*.72,0]} scale={[.55,1.15,.35]}><sphereGeometry args={[1,48,32]}/><MeshDistortMaterial color="#5b0610" emissive="#f52224" emissiveIntensity={1.8} distort={.42} speed={1.1+i*.08} transparent opacity={.8}/></mesh>)}<mesh><sphereGeometry args={[.48,48,48]}/><meshBasicMaterial color="#ff7a36"/></mesh></Rotating></Float>}
function Quantum(){return <Float speed={1.2} rotationIntensity={.35}><Rotating speed={.16}><mesh scale={1.32}><torusKnotGeometry args={[1,.28,280,48,2,5]}/><Glass color="#700818"/></mesh><mesh scale={1.33}><torusKnotGeometry args={[1,.285,100,12,2,5]}/><meshBasicMaterial color="#ff5065" wireframe transparent opacity={.16}/></mesh></Rotating></Float>}
function Singularity(){return <Rotating speed={.055}><mesh><sphereGeometry args={[1.05,64,64]}/><meshStandardMaterial color="#010101" metalness={1} roughness={.05}/></mesh><mesh rotation={[1.3,.2,.15]}><torusGeometry args={[1.45,.11,20,240]}/><MeshDistortMaterial color="#4b0008" emissive="#ff0928" emissiveIntensity={3} distort={.28} speed={1.6}/></mesh><mesh rotation={[1.3,.2,.15]} scale={1.18}><torusGeometry args={[1.45,.018,10,240]}/><meshBasicMaterial color="#ffb09a"/></mesh></Rotating>}

function ObjectById({id}:{id:VariantId}){switch(id){case"jellyfish":return <Jellyfish/>;case"sun":return <Sun/>;case"mercury":return <Mercury/>;case"lead":return <Lead/>;case"plasma":return <Plasma/>;case"blackhole":return <BlackHole/>;case"crystal":return <Crystal/>;case"bloom":return <Bloom/>;case"quantum":return <Quantum/>;default:return <Singularity/>}}
function Scene({id}:{id:VariantId}){return <Canvas camera={{position:[0,0,6.2],fov:38}} dpr={[1,1.6]} gl={{alpha:true,antialias:true}}><ambientLight intensity={.6}/><directionalLight position={[-4,5,4]} color="#fff0eb" intensity={3}/><pointLight position={[4,-2,3]} color="#ff1735" intensity={15}/><ObjectById id={id}/><Sparkles count={id==="sun"?110:55} scale={6} size={1.5} speed={.3} color={id==="mercury"||id==="lead"?"#dddde2":"#ff3045"}/><OrbitControls enableZoom={false} enablePan={false} autoRotate autoRotateSpeed={.35}/></Canvas>}

export default function VariantStudio(){const [selected,setSelected]=useState<VariantId>("jellyfish");const [chosen,setChosen]=useState<VariantId|null>(null);useEffect(()=>{const saved=localStorage.getItem("portfolio-3d-choice") as VariantId|null;if(saved&&variants.some(v=>v.id===saved))setChosen(saved)},[]);const current=variants.find(v=>v.id===selected)!;function choose(){localStorage.setItem("portfolio-3d-choice",selected);setChosen(selected)}return <main className="variant-lab"><header className="lab-head"><a href="/" className="lab-back"><ArrowLeft size={15}/> Портфолио</a><div><span>IVAN PETROV / OBJECT SYSTEM</span><i/>LIVE 3D</div></header><section className="lab-layout"><aside className="variant-list"><div className="lab-title"><p>/// 3D OBJECT LAB</p><h1>Выберите<br/><em>форму</em></h1><span>10 концепций для Hero-анимации</span></div><div className="variant-buttons">{variants.map(v=><button key={v.id} className={selected===v.id?"active":""} onClick={()=>setSelected(v.id)} style={{"--tone":v.tone} as React.CSSProperties}><span>{v.n}</span><i/><strong>{v.name}<small>{v.latin}</small></strong>{chosen===v.id&&<Check size={14}/>}</button>)}</div></aside><div className="lab-stage"><div className="stage-grid"/><div className="stage-label top">OBJECT / {current.n}</div><div className="stage-label side">{current.latin}</div><Scene key={selected} id={selected}/><div className="stage-info"><div><span>{current.n} / 10</span><h2>{current.name}</h2><p>{current.desc}</p></div><button onClick={choose} className={chosen===selected?"chosen":""}>{chosen===selected?<><Check size={16}/> Выбрано</>:<><SparkleIcon size={16}/> Выбрать вариант</>}</button></div><div className="stage-help"><span><MousePointer2 size={13}/> Вращайте мышью</span><span><Rotate3D size={13}/> Автоповорот включён</span></div></div></section></main>}
