"use client";

import Image from "next/image";
import { useState } from "react";
import { motion } from "framer-motion";
import { ArrowDown, ArrowUpRight, Boxes, Braces, Code2, Layers3, Mail, Menu, Send, ShoppingBag, Sparkles, X } from "lucide-react";
import HeroScene from "./components/HeroScene";

const projects = [
  {n:"01",title:"FinTrack",desc:"Платформа для управления финансами",tags:["Next.js","TypeScript","PostgreSQL"],type:"finance"},
  {n:"02",title:"ArchStudio",desc:"Сайт архитектурного бюро",tags:["React","GSAP","Tailwind CSS"],type:"arch"},
  {n:"03",title:"Travelino",desc:"Платформа для организации путешествий",tags:["Next.js","MongoDB","Stripe"],type:"travel"},
  {n:"04",title:"ShopSphere",desc:"Интернет-магазин с персонализацией",tags:["React","Redux","SCSS"],type:"shop"},
];
const skills=[{name:"React",v:94},{name:"Next.js",v:91},{name:"TypeScript",v:89},{name:"Node.js",v:82},{name:"Tailwind CSS",v:92},{name:"MongoDB",v:78},{name:"Git",v:88}];
const services=[{icon:Braces,title:"Frontend разработка",text:"Быстрые интерфейсы с безупречной логикой и деталями."},{icon:Boxes,title:"Web-приложения",text:"Масштабируемые платформы для бизнеса и пользователей."},{icon:ShoppingBag,title:"Интернет-магазины",text:"E-commerce решения, которые превращают трафик в продажи."},{icon:Layers3,title:"UI/UX разработка",text:"Чистый дизайн с фокусом на сценарии и конверсию."}];

const Reveal=({children,className=""}:{children:React.ReactNode,className?:string})=><motion.div className={className} initial={{opacity:0,y:28}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:"-80px"}} transition={{duration:.6}}>{children}</motion.div>;

function Navbar(){const [open,setOpen]=useState(false);const links=[["home","Главная"],["projects","Проекты"],["skills","Навыки"],["about","Обо мне"],["contact","Контакты"]];return <><header className="topbar"><a className="brand" href="#home"><span>&lt;</span>iv.dev<span>/&gt;</span></a><nav className="topnav">{links.map((l,i)=><a className={i===0?"active":""} href={`#${l[0]}`} key={l[0]}>0{i+1}. {l[1]}</a>)}</nav><a className="mini-cta" href="#contact">Связаться <i/></a><button className="menu" aria-label="Открыть меню" onClick={()=>setOpen(true)}><Menu size={20}/></button></header>{open&&<motion.div className="mobile-menu" initial={{opacity:0}} animate={{opacity:1}}><button aria-label="Закрыть меню" onClick={()=>setOpen(false)}><X/></button>{links.map((l,i)=><a onClick={()=>setOpen(false)} href={`#${l[0]}`} key={l[0]}><span>0{i+1}</span>{l[1]}</a>)}</motion.div>}</>}
function SideProfile(){return <aside className="side-profile"><div className="avatar"><Image src="/ivan-cyberpunk.png" alt="Иван Петров" fill sizes="64px"/></div><strong>Иван Петров</strong><span>Web Developer</span><div className="side-line"/><small><i/> AVAILABLE<br/><b>для новых проектов</b></small><div className="side-social"><a href="https://github.com" aria-label="GitHub"><Code2 size={15}/></a><a href="mailto:hello@ivanpetrov.dev" aria-label="Email"><Mail size={15}/></a></div></aside>}
function Hero(){return <section className="hero" id="home"><div className="hero-copy"><motion.p className="eyebrow" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}}>/// FRONTEND / FULLSTACK DEVELOPER</motion.p><motion.h1 initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{delay:.08}}>Создаю цифровые<br/>продукты, которые <em>работают</em></motion.h1><motion.p className="lede" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.18}}>Разрабатываю быстрые, красивые и функциональные сайты и веб-приложения для бизнеса.</motion.p><motion.div className="hero-actions" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{delay:.25}}><a className="button primary" href="#projects">Посмотреть проекты <ArrowUpRight size={17}/></a><a className="button secondary" href="#contact">Связаться со мной <Mail size={16}/></a></motion.div><div className="hero-meta"><span><Code2 size={15}/> React · Next.js · TypeScript</span><span className="availability"><i/> Доступен для проектов</span></div></div><div className="hero-art"><HeroScene/><span className="art-label l1">REALTIME / 01</span><span className="art-label l2">INTELLIGENCE</span></div><a className="scroll-hint" href="#stats"><ArrowDown size={14}/> SCROLL TO EXPLORE</a></section>}
function Stats(){return <section className="stats" id="stats">{[["20+","Проектов"],["3+","Года опыта"],["15+","Довольных клиентов"],["100%","Фокус на качестве"]].map(([n,t])=><Reveal className="stat" key={t}><strong>{n}</strong><span>{t}</span></Reveal>)}</section>}
function Projects(){return <section className="section" id="projects"><div className="section-head"><div><p className="eyebrow">/// ИЗБРАННЫЕ ПРОЕКТЫ</p><h2>Работы, которыми<br/>я <em>горжусь</em></h2></div><p>Каждый проект — баланс сильной идеи,<br/>чистого кода и измеримого результата.</p></div><div className="projects-grid">{projects.map(p=><Reveal className="project-card" key={p.title}><div className={`project-visual ${p.type}`}><div className="mock-top"><i/><i/><i/></div><div className="mock-ui"><span/><span/><span/><b/></div><small>VIEW / CASE</small></div><div className="project-body"><span className="project-no">{p.n}</span><a href="#contact" aria-label={`Открыть ${p.title}`}><ArrowUpRight/></a><h3>{p.title}</h3><p>{p.desc}</p><div>{p.tags.map(t=><span key={t}>{t}</span>)}</div></div></Reveal>)}</div></section>}
function About(){return <section className="section split-section" id="about"><Reveal className="about-card"><div className="about-image"><Image src="/ivan-cyberpunk.png" alt="Портрет Ивана Петрова" fill sizes="(max-width: 700px) 100vw, 40vw"/></div><div className="about-copy"><p className="eyebrow">/// ОБО МНЕ</p><h2>Создаю сайты и веб-приложения, которые <em>решают реальные задачи</em> бизнеса.</h2><p>Люблю чистый код, сложные интерфейсы и продуманные детали. Постоянно исследую новые технологии — и превращаю их в практическую пользу для продукта.</p><a href="#contact">Подробнее обо мне <ArrowUpRight size={16}/></a></div></Reveal><Reveal className="system-card"><p className="eyebrow">/// SYSTEM STATUS</p><div className="system-line"><i/><span>Everything is running</span><b>100%</b></div><div className="code-lines"><span/><span/><span/><span/></div><small>Последний деплой: сегодня, 14:32</small></Reveal></section>}
function Skills(){return <section className="section skill-section" id="skills"><div className="section-head"><div><p className="eyebrow">/// МОЙ СТЕК</p><h2>Технологии для<br/><em>сильных продуктов</em></h2></div><p>Инструменты меняются. Умение решать<br/>задачи остается главным.</p></div><div className="skills-layout"><Reveal className="radar"><div className="radar-grid"><i/><i/><i/><i/></div><div className="radar-core"><Sparkles/><span>FULLSTACK<br/>CORE</span></div>{skills.slice(0,6).map((s,i)=><span className={`radar-label r${i}`} key={s.name}>{s.name}</span>)}</Reveal><div className="skill-bars">{skills.map((s,i)=><Reveal className="skill-row" key={s.name}><span>{String(i+1).padStart(2,"0")}</span><strong>{s.name}</strong><div><motion.i initial={{width:0}} whileInView={{width:`${s.v}%`}} viewport={{once:true}} transition={{duration:1,delay:i*.05}}/></div><b>{s.v}%</b></Reveal>)}</div></div></section>}
function Services(){return <section className="section" id="services"><p className="eyebrow">/// ЧТО Я ДЕЛАЮ</p><div className="services-grid">{services.map((s,i)=><Reveal className="service-card" key={s.title}><span>0{i+1}</span><s.icon/><h3>{s.title}</h3><p>{s.text}</p><a href="#contact">Обсудить <ArrowUpRight size={15}/></a></Reveal>)}</div></section>}
function Contact(){return <section className="contact" id="contact"><div className="contact-glow"/><Reveal><p className="eyebrow">/// НАЧНЕМ ПРОЕКТ</p><h2>Готов обсудить<br/>ваш <em>проект</em></h2><p>Расскажите о задаче — отвечу в ближайшее время<br/>и предложу понятный следующий шаг.</p><a className="button primary" href="mailto:hello@ivanpetrov.dev">Написать мне <Send size={17}/></a></Reveal><div className="contact-links"><a href="mailto:hello@ivanpetrov.dev"><span>Email</span>hello@ivanpetrov.dev</a><a href="https://t.me/ivanpetrov_dev"><span>Telegram</span>@ivanpetrov_dev</a><a href="https://github.com"><span>GitHub</span>github.com/ivanpetrov</a></div></section>}
function Footer(){return <footer><a className="brand" href="#home"><span>&lt;</span>iv.dev<span>/&gt;</span></a><p>© 2026 Иван Петров. Создано с вниманием к деталям.</p><a href="#home">Наверх ↑</a></footer>}

export default function Home(){return <main><Navbar/><SideProfile/><div className="page"><Hero/><Stats/><Projects/><About/><Skills/><Services/><Contact/><Footer/></div></main>}
